"""add_resort_to_normalized_tours

Revision ID: 11269934679a
Revises: 32e277c4d2d4
Create Date: 2026-06-23 22:20:38.440833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11269934679a'
down_revision: Union[str, None] = '32e277c4d2d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_samo_dep_city_operator_id'), table_name='samo_departure_city')
    op.drop_table('samo_departure_city')
    op.add_column('normalized_tours', sa.Column('resort', sa.String(length=100), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('normalized_tours', 'resort')
    op.create_table('samo_departure_city',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('operator_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('city_inc', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], name=op.f('samo_departure_city_operator_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('samo_departure_city_pkey')),
    sa.UniqueConstraint('operator_id', 'city_inc', name=op.f('uq_samo_dep_city_op_inc'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_samo_dep_city_operator_id'), 'samo_departure_city', ['operator_id'], unique=False)
    # ### end Alembic commands ###