"""add hotel mapping table

Revision ID: 304aff457ed9
Revises: 730b17973693
Create Date: 2026-06-19 07:43:29.073637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '304aff457ed9'
down_revision: Union[str, None] = '730b17973693'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotel_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('raw_value', sa.String(length=300), nullable=False),
    sa.Column('canonical_hotel_id', sa.Integer(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operator_id', 'raw_value', name='uq_hotel_mapping_operator_raw')
    )
    op.create_index(op.f('ix_hotel_mapping_canonical_hotel_id'), 'hotel_mapping', ['canonical_hotel_id'], unique=False)
    op.create_index(op.f('ix_hotel_mapping_operator_id'), 'hotel_mapping', ['operator_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hotel_mapping_operator_id'), table_name='hotel_mapping')
    op.drop_index(op.f('ix_hotel_mapping_canonical_hotel_id'), table_name='hotel_mapping')
    op.drop_table('hotel_mapping')
    # ### end Alembic commands ###