"""add_pegas_departure_location_table

Revision ID: 3f849a87791b
Revises: YYYY_operator_session
Create Date: 2026-06-22 09:02:49.482759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3f849a87791b'
down_revision: Union[str, None] = 'YYYY_operator_session'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pegas_departure_location',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('airport_code', sa.String(length=10), nullable=True),
    sa.Column('is_top', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('airline_mapping', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_operator_id'), 'audit_logs', ['operator_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_profile_id'), 'audit_logs', ['profile_id'], unique=False)
    op.alter_column('comparison_results', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_comparison_results_created_at'), 'comparison_results', ['created_at'], unique=False)
    op.create_index(op.f('ix_comparison_results_scrape_run_id'), 'comparison_results', ['scrape_run_id'], unique=False)
    op.alter_column('meal_mapping', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('normalized_tours', 'scraped_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_normalized_tours_profile_id'), 'normalized_tours', ['profile_id'], unique=False)
    op.create_index(op.f('ix_normalized_tours_scrape_run_id'), 'normalized_tours', ['scrape_run_id'], unique=False)
    op.create_index(op.f('ix_normalized_tours_scraped_at'), 'normalized_tours', ['scraped_at'], unique=False)
    op.alter_column('operators', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('operators', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_pegas_hotel_resort_id'), table_name='pegas_hotel')
    op.drop_index(op.f('ix_pegas_resort_country_id'), table_name='pegas_resort')
    op.alter_column('price_snapshots', 'recorded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_price_snapshots_normalized_tour_id'), 'price_snapshots', ['normalized_tour_id'], unique=False)
    op.create_index(op.f('ix_price_snapshots_recorded_at'), 'price_snapshots', ['recorded_at'], unique=False)
    op.alter_column('raw_results', 'scraped_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_raw_results_scraped_at'), 'raw_results', ['scraped_at'], unique=False)
    op.alter_column('room_mapping', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('search_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('search_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('search_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('search_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('room_mapping', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_raw_results_scraped_at'), table_name='raw_results')
    op.alter_column('raw_results', 'scraped_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_price_snapshots_recorded_at'), table_name='price_snapshots')
    op.drop_index(op.f('ix_price_snapshots_normalized_tour_id'), table_name='price_snapshots')
    op.alter_column('price_snapshots', 'recorded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_pegas_resort_country_id'), 'pegas_resort', ['country_id'], unique=False)
    op.create_index(op.f('ix_pegas_hotel_resort_id'), 'pegas_hotel', ['resort_id'], unique=False)
    op.alter_column('operators', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('operators', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_normalized_tours_scraped_at'), table_name='normalized_tours')
    op.drop_index(op.f('ix_normalized_tours_scrape_run_id'), table_name='normalized_tours')
    op.drop_index(op.f('ix_normalized_tours_profile_id'), table_name='normalized_tours')
    op.alter_column('normalized_tours', 'scraped_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('meal_mapping', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_comparison_results_scrape_run_id'), table_name='comparison_results')
    op.drop_index(op.f('ix_comparison_results_created_at'), table_name='comparison_results')
    op.alter_column('comparison_results', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_audit_logs_profile_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_operator_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('airline_mapping', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_table('pegas_departure_location')
    # ### end Alembic commands ###