"""add city and country mapping tables

Revision ID: 5a57856e7d03
Revises: 0001
Create Date: 2026-06-18 09:20:02.680689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '5a57856e7d03'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('raw_value', sa.String(length=200), nullable=False),
    sa.Column('normalized_value', sa.String(length=100), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operator_id', 'raw_value', name='uq_city_mapping_operator_raw')
    )
    op.create_index(op.f('ix_city_mapping_operator_id'), 'city_mapping', ['operator_id'], unique=False)
    op.create_table('country_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('raw_value', sa.String(length=200), nullable=False),
    sa.Column('normalized_value', sa.String(length=100), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operator_id', 'raw_value', name='uq_country_mapping_operator_raw')
    )
    op.create_index(op.f('ix_country_mapping_operator_id'), 'country_mapping', ['operator_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_country_mapping_operator_id'), table_name='country_mapping')
    op.drop_table('country_mapping')
    op.drop_index(op.f('ix_city_mapping_operator_id'), table_name='city_mapping')
    op.drop_table('city_mapping')
    # ### end Alembic commands ###