"""add kazunion catalog tables

Revision ID: 5d2aafdbb3cf
Revises: 81bc332da77e
Create Date: 2026-06-25 08:57:48.652593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d2aafdbb3cf'
down_revision: Union[str, None] = '81bc332da77e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kazunion_country',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('samo_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('samo_id'),
    sa.UniqueConstraint('samo_id', name='uq_kazunion_country_samo_id')
    )
    op.create_table('kazunion_resort',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ht_place_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country_samo_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ht_place_id'),
    sa.UniqueConstraint('ht_place_id', name='uq_kazunion_resort_ht_place_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kazunion_resort')
    op.drop_table('kazunion_country')
    # ### end Alembic commands ###