"""add auto_matched to hotel_mapping

Revision ID: 68edbbdd386a
Revises: f2da47b0af54
Create Date: 2026-06-25 11:36:30.239304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68edbbdd386a'
down_revision: Union[str, None] = 'f2da47b0af54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('hotel_mapping', sa.Column('auto_matched', sa.Boolean(), nullable=False, server_default='false'))
    op.alter_column('hotel_mapping', 'auto_matched', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotel_mapping', 'auto_matched')
    # ### end Alembic commands ###