"""add tour program mapping table

Revision ID: 730b17973693
Revises: 5a57856e7d03
Create Date: 2026-06-18 11:46:04.277652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '730b17973693'
down_revision: Union[str, None] = '5a57856e7d03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tour_program_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('raw_value', sa.String(length=200), nullable=False),
    sa.Column('normalized_value', sa.String(length=100), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operator_id', 'raw_value', name='uq_tour_program_mapping_operator_raw')
    )
    op.create_index(op.f('ix_tour_program_mapping_operator_id'), 'tour_program_mapping', ['operator_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tour_program_mapping_operator_id'), table_name='tour_program_mapping')
    op.drop_table('tour_program_mapping')
    # ### end Alembic commands ###