"""add_selfie_catalog_v2

Revision ID: 81bc332da77e
Revises: 9418c67068a2
Create Date: 2026-06-24 09:28:59.902955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81bc332da77e'
down_revision: Union[str, None] = '9418c67068a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('selfie_country',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('samo_departure_city',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('city_inc', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operator_id', 'city_inc', name='uq_samo_dep_city_op_inc')
    )
    op.create_index(op.f('ix_samo_departure_city_operator_id'), 'samo_departure_city', ['operator_id'], unique=False)
    op.create_table('selfie_resort',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['selfie_country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('selfie_resort')
    op.drop_index(op.f('ix_samo_departure_city_operator_id'), table_name='samo_departure_city')
    op.drop_table('samo_departure_city')
    op.drop_table('selfie_country')
    # ### end Alembic commands ###