"""add funsun catalog tables

Revision ID: af1a5c044ca5
Revises: 68edbbdd386a
Create Date: 2026-06-28 11:25:00.002799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af1a5c044ca5'
down_revision: Union[str, None] = '68edbbdd386a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###