"""add funsun catalog tables

Revision ID: cb0c7646b45c
Revises: af1a5c044ca5
Create Date: 2026-06-28 12:19:02.312778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb0c7646b45c'
down_revision: Union[str, None] = 'af1a5c044ca5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funsun_country',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('samo_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('samo_id'),
    sa.UniqueConstraint('samo_id', name='uq_funsun_country_samo_id')
    )
    op.create_table('funsun_resort',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ht_place_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country_samo_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ht_place_id'),
    sa.UniqueConstraint('ht_place_id', name='uq_funsun_resort_ht_place_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('funsun_resort')
    op.drop_table('funsun_country')
    # ### end Alembic commands ###