"""add kazunion catalog tables

Revision ID: f2da47b0af54
Revises: 5d2aafdbb3cf
Create Date: 2026-06-25 08:59:34.661030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2da47b0af54'
down_revision: Union[str, None] = '5d2aafdbb3cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###